sudo: false
dist: focal
language: python
services:
  - postgresql

python:
  - "3.8"

env:
  - DJANGO="Django>=2.2,<3.0"
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="Django>=3.1,<3.2"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

before_install: pip install --upgrade pip

install: pip install $DJANGO pytest pytest-django pytest-cov psycopg2-binary

script: pytest --cov=mpathy
